### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/onehomeowner.com#1]
@codextiny 
[https://onehomeowner.homeowner.ai/](url)

Same credentials as the other sites. Can you help align this section? 
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/8c9c9f28-0161-4c34-a3bb-2ab5e1c67ac5)

**Comment by shannonbaldwin** [comment]
@codextiny 
I cannot get the hover color to be the accent color without the border color coming through on[ this page.]([https://onehomeowner.homeowner.ai/](https://github.com/shannonbaldwin/onehomeowner.com/issues/url))
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/4944f7d8-6d77-4064-bca9-bd63aba1e01d)[
](https://onehomeowner.homeowner.ai/)[https://onehomeowner.homeowner.ai/](https://github.com/shannonbaldwin/onehomeowner.com/issues/url)

**Comment by shannonbaldwin** [comment]
@codextiny
Can you please help align these logos in the footer on the same URL above?
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/a7a8c168-e200-44fe-a25e-62af3ca6cfa9)

**Comment by codextiny** [comment]
@shannonbaldwin 

We have fixed all above mentioned issues, please check and let us know if you have any issue .

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny 
[https://onehomeowner.com/](url)
Need same custom coding here for this video and the black outline removed. 
support@milestones.ai
M!l3st0nesL@bs

![image](https://github.com/user-attachments/assets/6753d280-69a9-4671-a00e-72edfc8c3ca4)

**Comment by codextiny** [comment]
@shannonbaldwin 

It's done please check
